name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies and build (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential meson
          meson setup build
          meson compile -C build
          
      - name: Install dependencies and build (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gcc meson
          meson setup build
          meson compile -C build

      - name: Set up Scoop and install GCC/make (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
          irm get.scoop.sh | iex
          scoop install gcc meson python ninja pkg-config winflexbison
          meson setup build
          meson compile -C build